# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-4.4.1
apiVersion: v1
kind: Pod
metadata:
  annotations:
    org.opencontainers.image.base.digest/mydevcontainer: sha256:877f74c95983f9e5d175415a9dd908abaafc1259476da611702d9c55
    org.opencontainers.image.base.name/mydevcontainer: registry.access.redhat.com/ubi8/ubi-init:latest
  creationTimestamp: "2023-10-09T20:15:26Z"
  labels:
    app: my-lamp
  name: my-lamp
spec:
  containers:
  - args:
    - /sbin/init
    image: localhost/httpd-php:1.0
    name: mydevcontainer
    ports:
    - containerPort: 80
      hostPort: 8080
    resources: {}
    securityContext:
      readOnlyRootFilesystem: true
    volumeMounts:
    - mountPath: /var/log
      name: tmp-0
    - mountPath: /var/tmp
      name: tmp-1
    - mountPath: /var/www/html/
      name: home-juancvilla-lamp1-html-host-2
  - args:
    - run-mysqld
    env:
    - name: MYSQL_USER
      value: user
    - name: MYSQL_PASSWORD
      value: pass
    - name: MYSQL_DATABASE
      value: db
    image: registry.redhat.io/rhel8/mariadb-103:latest
    name: mariadbdatabase
    resources: {}
    securityContext:
      runAsNonRoot: true
    volumeMounts:
    - mountPath: /var/lib/mysql
      name: home-juancvilla-lamp1-mysql-host-0
  hostname: my-lamp
  restartPolicy: Never
  volumes:
  - hostPath:
      path: /home/juancvilla/lamp1/mysql
      type: Directory
    name: home-juancvilla-lamp1-mysql-host-0
  - emptyDir:
      medium: Memory
    name: tmp-0
  - emptyDir:
      medium: Memory
    name: tmp-1
  - hostPath:
      path: /home/juancvilla/lamp1/html
      type: Directory
    name: home-juancvilla-lamp1-html-host-2
status: {}
